### ISSUE TITLE
~RunningAverage() deconstructor to free the memory allocated?

### ISSUE THREAD

**Issue by Harry-ei6ku** [RobTillaart/RunningAverage#11]
A novice question on C++
 Is it valid to both construct RunningAverage(size)
and deconstruct RunningAverage in the main loop, 
ie to free up ram for another part of the main loop?
or must construct Running Average be set outside the setup and mail loops?

**Comment by RobTillaart** [comment]
If you reuse the data you added to the running average object (which is the case in most projects) you should create the object outside setup() and loop().

If you want to have a temporary RA object then you should create it in the function of your choice. 
And I would call the destructor as soon as possible.

**Comment by RobTillaart** [comment]
That said, if you are running out of RAM you must either redesign your program or you need a processor with (some) more RAM.

ANother option could be to add an FRAM or EEPROM module or even an SD card if you need some (semi) persistent storage.

**Comment by Harry-ei6ku** [comment]
Thanks Rob, yes all understood, a temp RA will work for my project, I'll move them into a function.
One further Q pls if u have time, I'm using two RA buffers, so will "~RunningAverage() " deconstruct both of them or can I choice which to deconstruct?
73
H

**Comment by RobTillaart** [comment]
You are the programmer so you can decide where and when.tovdestruct one or both.
From memory management point of view calling mallic and free over and over again is not considered good architecture for embedded. Better to allocate it once and clear the thing when the function is called.

**Comment by Harry-ei6ku** [comment]
Tks Rob, appreciate
