### ISSUE TITLE
Request for new partial "get" functions

### ISSUE THREAD

**Issue by patfelst** [RobTillaart/RunningAverage#15]
Hi Rob, could you please consider implementing "partial" versions for some of the get functions? e.g. `float RunningAverage::getPartialAverage(uint16_t points)` where points specifies how many of the most recent points to use in the calculation. I think just the getAverage, getMaxInBuffer, getMinInBuffer for starters. It wouldn't work for the fast average, but I'm not worried about that.

I guess you could even modify the existing functions and if `getSize()` or `getCount()` is passed in, it calculates the value based on all points added to the buffer so far.

The reason I ask is I have a large buffer to store sensor history, but due to screen size limitation, I'm only displaying a portion of the data, and want to easily display min/max/average stats which are correct for the partial "displayed" data. I use the full history for some other calculations.

I guess another solution would be for me to have two circular buffers, one large for storing the full history data, and another smaller version which stores a copy of the subset for display purposes as I have plenty of RAM on the ESP32. Not so good for smaller Atmel type microcontrollers.

Thanks

**Comment by RobTillaart** [comment]
Sounds like an interesting addition. It might have more purposes than we can think of right away. 

I will give it a try today.

**Comment by RobTillaart** [comment]
Created - https://github.com/RobTillaart/RunningAverage/tree/last + PR
Feel free to do some tests 

## Last

These functions get the basic statistics of the last N added elements.
Returns NAN if there are no elements and it will reduce count
if there are less than count elements.

- **float getAverageLast(uint16_t count)** get the average of the last count elements.
- **float getMinInBufferLast(uint16_t count)** get the minimum of the last count elements.
- **float getMaxInBufferLast(uint16_t count)** get the maximum of the last count elements.

**Comment by RobTillaart** [comment]
fix pushed

**Comment by patfelst** [comment]
Thanks very much! I will try it tonight and report back.

**Comment by patfelst** [comment]
I tried it quickly before work, so don't have time to debug, but from a quick look, somethings not quite right when the number of points added to the buffer is less than the number of points I pass in to calculate the average over. So the average is too low.

I think this line:
`return _sum / count;`
should be
`return _sum / _count;`

Thanks again for such a fast update!

**Comment by RobTillaart** [comment]
Ney, count can be too high.

**Comment by RobTillaart** [comment]
fixed in last with cnt2

```cpp
float RunningAverage::getAverageLast(uint16_t count)
{
  uint16_t cnt = count;
  if (cnt > _size) cnt = _size;
  if (cnt > _count) cnt = _count;
  if (cnt == 0) return NAN;
  uint16_t cnt2 = cnt;   // cnt2 is adjusted for _size and _count

  uint16_t idx = _index;
  if (idx == 0) idx = _size;
  idx--;
  float _sum = 0;
  while (cnt > 0)
  {
    _sum +=_array[idx];
    if (idx == 0) idx = _size;
    idx--;
    cnt--;
  }
  return _sum / cnt2;
}
```

I need to look if I can clean up the code a bit (it becomes a bit less readable)

**Comment by patfelst** [comment]
I will try this tonight. Could this be more readable, based on your original average function:

```C++
float RunningAverage::getAverageLast(uint16_t count)
{
  if ((_count == 0) || (count == 0))
  {
    return NAN;
  }

  _sum = 0;
  for (uint16_t i = 0; i < _count && i < count; i++)
  {
    _sum += _array[i];
  }
  return _sum / ( i+ 1);
}
```

**Comment by RobTillaart** [comment]
Looks good.
the internal buffer is circular, that should be included. In my code idx goes from the last added and goes backwards.

**Comment by RobTillaart** [comment]
I have updated the code, please have a look.

**Comment by patfelst** [comment]
Hey Rob, I've tested your latest, .getMinInBufferLast(), .getAverageLast(), .getMaxInBufferLast() and all working perfectly.

Thanks so much, appreciate your good work! I find the new version with for loop more readable too.

**Comment by RobTillaart** [comment]
Thanks for testing!
Will merge code later this week. Is there any specific use case I should mention in the readme.md for the functions?

**Comment by patfelst** [comment]
Sounds good. The readme could say:

> .getMinInBufferLast(), .getAverageLast(), .getMaxInBufferLast() are useful in cases where you might want to display a subset of data from a circular buffer and calculate statistics on just the displayed subset

**Comment by RobTillaart** [comment]
Ok will be added.

Was thinking about a default value for the **count** parameter. The only number I can think of is **zero**. As that would make no sense normally it could have the special meaning of **all**.

No default value however forces the user to see the difference with the 'normal' functions, leaving less room for mistakes 

Opinion?
(My choice for now is no default, as I prefer 'thinking users')

**Comment by RobTillaart** [comment]
readme pushed

**Comment by patfelst** [comment]
I don't think a default count parameter is necessary, like you say, this forces the user to understand the function before using. If a default of zero means use all points, they should be using `getAverage()` anyway.

Or you want to "simplify" the library and combine the two functions into one using class overloading? But even then you don't need a default count. Calling with no parameter uses all points, or calling with a count uses that number of points.

I think just leave it as-is for now.

**Comment by RobTillaart** [comment]
merged and released,
if there are other issues or questions, let me know

**Comment by Teddyz** [comment]
I think getAverageLast() can do the same job as the Partial functions for me. If you see any benefit of removing partial it is OK for me to change my programs to use Last instead.

**Comment by RobTillaart** [comment]
@Teddyz 
Both have different applications and behavior, although these might functional overlap sometimes.

Using getAverageLast(n) can vary the value of n per call without changing the internal buffer.
Partial is more a semi-permanent reduction of the use of the internal buffer.

So I see no reason to remove one or the other.
(hope this helpes)

**Comment by Teddyz** [comment]
Not changing the internal buffers is good for me, so I will use this function instead. You are very helpful. Thank you.
