### ISSUE TITLE
A way to backup content?

### ISSUE THREAD

**Issue by Teddyz** [RobTillaart/RunningAverage#21]
I use RunningAverage to store values from a Barometer and a  Thermometer.  I do not only get min/max/average, but also draw a graph.  It works fine until the Arduino restarts I lose all data, and It will take a day to fill the graphs again.

Is there a way to backup all values so they can survive a reboot? I understand that I can iterate through all values and save somewhere, but is there a smarter way? I guess that If I had a blob of bytes it could be saved to a file every 30 minutes or so.

**Comment by RobTillaart** [comment]
Thanks fot this issue,
It is a really good question I have never considered.
Might take a few days before i can investigate.

**Comment by RobTillaart** [comment]
Idea. 
If you store min max and avg to a file you can sort of recreate an approximation of the state.
Use filValue(avg) add(min) and add(max) to create a state that would keep graphs smooth (not tested).
Advantage: 
- only 3 values needed to store (independant of size)
- can be implemented without change
- smooth graphs
Disadvantage
- not correct as it can and will break trendlines.

**Comment by RobTillaart** [comment]
One solution could be a **save(byte \* buffer)** and a **load(byte \* buffer)**. Serialization of whole internal state.

Another solution would be **float getValueByTime(n)** to extract the internal array so it can be restored by **add()** the values in order.

**Comment by RobTillaart** [comment]
(so lets look at my nightly thoughts)

- **float getValueByTime(n)** already exists, it is just **float getValue(position)**.

**getValue()** allows users to extract all values individually and process them.  Restoring the data is just **addValue()** as said before. Think of extracting the temperatures in Celsius and restore them in Fahrenheit, remove outliers, or add an offset.
This can be done in a loop.
```cpp
for (int i = 0; i < RA.size; i++)
{
  float val = RA.getValueByTime(i);
  RA.addValue(process(val));
}
```

Serializing / storing the RA object can be written with the **getValue()**, **getMax()** and **getMin()**. The latter two are needed as these might exceed the min and max currently in the internal buffer.

In pseudo-code

```cpp
void saveRA()
{
  //  open some persistent store (PS)  - SD card, FRAM, EEPROM, website whatever.
  PS.open(....);
  PS.writeFloat(RA.getMin());
  PS.writeFloat(RA.getMax());
  for (int i = 0; i < RA.size; i++)
  {
    PS.writeFloat(RA.getValue(i));
  }
  PS.close();
}
 
void restoreRA()
{
  //  open some persistent store (PS)  - SD card, FRAM, EEPROM, website whatever.
  PS.open(....);
  RA.reset();
  RA.addValue(PS.readFloat()):  //  MIN
  RA.addValue(PS.readFloat()):  //  MAX
  while (PS.available())
  {
    RA.addValue(PS.readFloat()):
  }
  PS.close();
}
```
----

The first idea to store just the **min** **max** and **avg** still makes sense if you want to minimize the storage requirements, both in bytes needed and time needed - writing 3 floats is faster than e.g. write 

```cpp
void saveRA()
{
  //  open some persistent store (PS)  - SD card, FRAM, EEPROM, website whatever.
  PS.open(....);
  PS.writeFloat(RA.getMin());
  PS.writeFloat(RA.getMax());
  PS.writeFloat(RA.getAverage(i));
  PS.close();
}
 
void restoreRA()
{
  //  open some persistent store (PS)  - SD card, FRAM, EEPROM, website whatever.
  PS.open(....);
  RA.reset();
  RA.addValue(PS.readFloat()):  //  MIN
  RA.addValue(PS.readFloat()):  //  MAX
  RA.FillValue(PS.readFloat()):   //  AVG
  PS.close();
}
```

**Comment by RobTillaart** [comment]
So coming back to your original question

> I understand that I can iterate through all values and save somewhere, but is there a smarter way?

The library does not support a smarter way as it cannot know how the user wants to store the "blob". 
Device, file name, URL etc

What I did in some projects is to create a separate .h file with helper functions (wrappers like above) tuned for the need of that specific project. That keeps the code of my core code relative clean.

**Comment by Teddyz** [comment]
I decided to try saving to rtc-ram, which survives reset on ESP8266 and ran into a second problem. 
Memory shortage. I want to save enough data to be able to show a graph. So 90 data points, covering 45 hours is needed.
Floats are too big, so I decided to sacrifice both convenience and precision.

```cpp
#include <RTCMemory.h>
typedef struct { // MAX 384 bytes if using OTA on ESP8266
  int16_t RA_utetemp_last_30m[90];
  int16_t RA_utetemp_24h_min[24];
  int16_t RA_utetemp_24h_max[24];
  uint8_t RA_utetemp_last_30m_count = 0;
  uint8_t RA_utetemp_24h_min_count = 0;
  uint8_t RA_utetemp_24h_max_count = 0;
  uint8_t RA_barometer_30m[90];
  uint8_t RA_barometer_30m_count = 0;
  uint16_t reset_count_valid_RTC = 0;
  time_t last_save_time; 
} RTCdata; // using 374 bytes. Hopefully OK
RTCMemory<RTCdata> rtcMemory;
RTCdata *rtc;
```

Save and restore for these looks similar to yours:
```cpp
void rtc_save() {
  int16_t i;
  for (i = 0; i < RA_utetemp_last_30m.getCount(); i++) { // oldest value will be saved first in array
    rtc->RA_utetemp_last_30m[i] = RA_utetemp_last_30m.getValue(i) * 10;
  }
  rtc->RA_utetemp_last_30m_count = i;

  for (i = 0; i < RA_utetemp_24h_min.getCount(); i++) {
    rtc->RA_utetemp_24h_min[i] = RA_utetemp_24h_min.getValue(i) * 10;
  }
  rtc->RA_utetemp_24h_min_count = i;

  for (i = 0; i < RA_utetemp_24h_max.getCount(); i++) {
    rtc->RA_utetemp_24h_max[i] = RA_utetemp_24h_max.getValue(i) * 10;
  }
  rtc->RA_utetemp_24h_max_count = i;

  for (i = 0; i < RA_barometer_30m.getCount(); i++) {
    rtc->RA_barometer_30m[i] = RA_barometer_30m.getValue(i) - 900; // barometer values are within 950 and 1050 hPa. Saves 3bytes/reading, but lose decimals
  }
  rtc->RA_barometer_30m_count = i;

  rtc->last_save_time = local(); // now() adjusted for timezone and dst
  rtcMemory.save();
}

void rtc_init_and_load() {
  int16_t i;
  bool ok = rtcMemory.begin(); // true if valid content in ESP8266 unused rtc memory.
  rtc = rtcMemory.getData();
  if (ok) {
    for (i = 0; i < rtc->RA_utetemp_last_30m_count; i++) { // reading oldest value first
      RA_utetemp_last_30m.addValue((float)rtc->RA_utetemp_last_30m[i] / 10);
    }

    for (i = 0; i < rtc->RA_utetemp_24h_min_count; i++) {
      RA_utetemp_24h_min.addValue((float)rtc->RA_utetemp_24h_min[i] / 10);
    }

    for (i = 0; i < rtc->RA_utetemp_24h_max_count; i++) {
      RA_utetemp_24h_max.addValue((float)rtc->RA_utetemp_24h_max[i] / 10);
    }

    for (i = 0; i < rtc->RA_barometer_30m_count; i++) {
      RA_barometer_30m.addValue(rtc->RA_barometer_30m[i] + 900);
    }
    rtc->reset_count_valid_RTC++;
    rtcMemory.save(); //Just save the increased counter if reset again before any new value is stored. No new value to last_save_time.
    log( F("rtc_init_and_load"), 1, p( G( "Using rtc %d times. Last saved %s. RA_utetemp_last_30m_count=%d RA_utetemp_24h_min_count=%d RA_barometer_30m_count=%d" ),
                                       rtc->reset_count_valid_RTC, datetime_char(rtc->last_save_time), rtc->RA_utetemp_last_30m_count, rtc->RA_utetemp_24h_min_count, rtc->RA_barometer_30m_count) );
  }
  else {
    log( F("rtc_init_and_load"), 1, G( "Using rtc 0 times, no valid rtc memory.")); // log() is my own logfile function. G() is a macro to save character arrays in flash.
  }
}
```
I am not sure if it still will work when RA is full and starts throwing out old values. (Will save and restore put them back at correct positions, will I lose first/last value?)

Here is an example of a graph from earlier today, with original size is 96x128px. Graph made using the library OLED_SSD1306_Chart. (Using no real oled, instead making canvas larger and moving bits into a bmp that is sent via mqtt to the app MQTT Dash on Android.)
![bild](https://user-images.githubusercontent.com/14166139/210673115-a1d2cf88-3ab9-4a1a-893d-753fe54ad532.png)

Thanks for looking into this! Ok to close.

**Comment by RobTillaart** [comment]
Mmm, lets think
You could try delta coding to save memory.
Store the first value as float, and the next values as offset to the previous as an int8. assumption is that two consecutive temperature do not differ more than 12.7 degrees.
Assume you have 25.6 25.6 25.9 30.0 28.1...
That would encode 25.6. 0 3 41 -19 etc

138 floats will be compressed from 352  bytes to about 150 bytes. Would be almost factor 2 better than your scheme. As temperature seldom drops or raises 12 degrees within a minute it might just work.

**Comment by RobTillaart** [comment]
For pressure you use a fixed reference of 900. That is also delta coding.
What I propose is not to use a fixed reference but use the previous value as new reference.

**Comment by Teddyz** [comment]
The updates are 30 minutes apart and sometimes the sun finds the probe, so delta codng temperature to save bytes might go wrong. I guess the delta-encoder can be made aware of too big leaps and limit changes, but that would need careful thinking when writing the program.

But for the barometer, using a non-fixed start-value is great. Preserving the decimals will make the graph smoother if the backup is needed. Thanks!

**Comment by RobTillaart** [comment]
> I guess the delta-encoder can be made aware of too big leaps and limit changes, but that would need careful thinking when writing the program.

true, one need at least a special code e.g 0xFF to indicate the next value is a new absolute value. Not to difficult, but there are some pitfalls. Worst case if the values varies a lot the compression works in "reverse" and in fact expends.
