### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by ahmetcemturan** [RobTillaart/RunningAverage#22]
Hi Rob,
I would like to know whether the ringbuffer lnegth is settable (like with the Running Angle).
Also is the code ready for production?  I like the max min option a lot and would like to use it.  (Along with a settable length)

**Comment by RobTillaart** [comment]
> I would like to know whether the ringbuffer lnegth is settable (like with the Running Angle).

You can set the size in the constructor.

> Also is the code ready for production?

The code is stable for quite some time now. There is no warranty, so use it at your own risc (see MIT license). 
That said if there are bugs or other problems you can always open an issue and I will try to help.

>  I like the max min option a lot and would like to use it.

Best is to first make a small prototype to verify if the library meets your requirements.

**Comment by ahmetcemturan** [comment]
How could I have missed that :(
I have implemented t now for a weather station where I measure 3 different lengths of averages for the wind.  1min, 5min and 10min average alng with the respective max and min winds.  I noticed that the max and min values have to be reset after these periods as there is basically no "period" in the rolling buffer..

**Comment by RobTillaart** [comment]
> I noticed that the max and min values have to be reset after these periods as there is basically no "period" in the rolling buffer..

You can use **getMinInBuffer()** and **getMaxInBuffer()**

**Comment by ahmetcemturan** [comment]
Oh great, you are so helpful...
Thanks a lot.

**Comment by RobTillaart** [comment]
If there are no more questions, you may close the issue.
