### ISSUE TITLE
Is a 'rolling' max possible?

### ISSUE THREAD

**Issue by terrypin999** [RobTillaart/RunningAverage#26]
I want to show the max (and min) 'rolling' values recorded from a stream during the previous 7 days. IOW, keep replacing the oldest with the most recent. Is that possible with this library please?

**Comment by RobTillaart** [comment]
Please check if my **minmax** library fit your needs.

**Comment by RobTillaart** [comment]
Note this library has 
- **getMin()** that shows the minimum since last reset
- **getMinInBuffer()**.that shows the minimum of the last N samples where N is the size of the **runningAverage* object
-

**Comment by terrypin999** [comment]
Thanks for fast response. I had tried with minmax_demo before posting but no joy. Happy to post my feeble edit if it helps, but on day 8  it was not replacing the max from day 1 with the max from day 8. Almost certainly down to my not fully understanding the library. I was hoping one of you many examples would provide an easy to copy basis.

Note: this will be integrated into a fairly complex project with DallasTemperaure reading, RTC and LCD.

**Comment by RobTillaart** [comment]
Ok, think I understand your requirements a little better now.

Idea:
What you could do is create a second RA object  called RA2 with size 14. At the end of every day you get the min and max of that day from RA1 and put it in RA2. 
Then the RA2 will constantly have the min and max of the last 7 days in its internal buffer. When adding the values for say 8, the values for day 1 will be overwritten.

Does this idea meet your needs?

**Comment by terrypin999** [comment]
Thanks Rob, I’ll be back on the case after breakfast and will try that
clever idea.
Best Wishes,
Terry Pinnell, East Grinsted, UK

**Comment by RobTillaart** [comment]
@terrypin999 
Any progress?

**Comment by terrypin999** [comment]
Thanks for asking. A little progress, but It's proving harder than I'd
hoped. I've spent considerable time on simulating the midnight change from
Yesterday to Today. Needed before calling my functions to speak min & max
temperatures, etc.

So for the time being I've postponed coding reports of min & max for 'the
previous seven days'. I'll return to that later but meanwhile I'm focusing
on just Today and Yesterday. That's also the fastest route to getting the
project cased, as my breadboard version is not robust.

**Comment by RobTillaart** [comment]
Created a PR with the new example (and some more)
Will merge later this week.

**Comment by terrypin999** [comment]
Thanks a lot Rob. Appreciate your patient help. Have not yet run it but looks good, and expect to do so soon.Happy meanwhile for you to close the ‘issue’.Best Wishes,--TerryOn 18 Oct 2023, at 15:47, Rob Tillaart ***@***.***> wrote:﻿
Created a PR with the new example (and some more)
Will merge later this week.

**Comment by RobTillaart** [comment]
Please let me know if the solution works "runtime".
Feel free to reopen the issue when needed.
