### ISSUE TITLE
Would you consider adding function to "RunningAverage"

### ISSUE THREAD

**Issue by heidnerd** [RobTillaart/RunningAverage#30]
I'm working with sensors - most of the time the interval between sensing periods is very close such that a simple running average for the hour, 8 hour or day works fine.   However I've also been working to make the sensing packages reduce energy if the battery appears to be dropping - and that typically means stretching out time between samples.

This means the data needs to be time weighted averages (TWA).

Easy way is to use the RunningAverage liibrary.  In the application use TWO circular buffers,  the first will be the numerator in calculating TWA,  the second would contain the values for the denominator.

```cpp
TWA =  Sum_of (delta_T X sensor_value) / (Sum_of (delta_T))
```

By using the existing library,  it's now possible to use your existing functions to find the jitter in the interval between measurements.  That jitter or variation can mean a lot in the accuracy...

Your existing library code  with new function like:

```cpp
// 
float RunningAverage::getsum() const
{
  if (_count == 0)
  {
    return NAN;
  }

  return _sum;   // 
}
```

(added syntax highlighting)

**Comment by RobTillaart** [comment]
Thanks for sharing,
Sounds like an interesting addition. And I need to think about how it affects existing projects. A derived class might be tight choice.

**Comment by RobTillaart** [comment]
@heidnerd 
Could it be interesting to make the weight more generic?
Default weight is 1, your proposal the weight is time, however it could also be an other unit. 

This would imply that **addValue(value, weight = 1)** would allow the user to add any weight it wants to,

It would also solve a "time problem" for the first sample, the library cannot add a weight to it, so it should be zero.?

**Comment by RobTillaart** [comment]
@heidnerd 
Created a first implementation of a **RA_weight** class in the develop branch.
It is derived from RunningAverage and implements the core functions to add a value and to get average.

Note however that not all functionality is implemented with weight (needs investigation if they make sense and how)
The outcome might be a stand alone repo with a stripped interface.

**Comment by RobTillaart** [comment]
Note: https://en.wikipedia.org/wiki/Weighted_arithmetic_mean

**Comment by RobTillaart** [comment]
@heidnerd 
Note: I kept the implementation in the RA_weight class pretty generic so people have to add the weight themselves with **addValue(value, weight)**. If none is given the weight == 1.

This allows you to add the duration as weight and other people using theirs.

Please let me know if there is functionality missing that would logically fit into the RA_weight class.

**Comment by heidnerd** [comment]
I can come up with some examples.   Pretty simple examples of the TWA 
and the interval jitter is useful.

I can add in the section of code and see how that works - but I really 
don't like forking libraries unnecessarily.

---

Dennis Heidner

(206) 817-1164
On 2024-06-24 20:44, Rob Tillaart wrote:

> Thanks for sharing,
> Sounds like an interesting addition. And I need to think about how it 
> affects existing projects. A derived class might be tight choice.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/RobTillaart/RunningAverage/issues/30#issuecomment-2187911479
[2]

**Comment by RobTillaart** [comment]
> I can come up with some examples.   Pretty simple examples of the TWA
and the interval jitter is useful.

That would be very informative as keeping the API close to real use cases is good (imho).

----

> I can add in the section of code and see how that works 

Your feedback is welcome

----

> but I really don't like forking libraries unnecessarily.

Agree, 
however in my experience the Arduino (IOT) ecosystem is very diverse. I have seen projects working with tiny processors with 2K Ram or less running on 1 MHz and on the other end things like ESP32's with plenty room to spare at 240 MHz and beyond. For me in my role as (Arduino) library developer I must guard that performance and footprint is more or less stable over versions, especially for often used libraries like RA. Furthermore the interface must be kept simple to not confront new tinkers with steep learning curves (adding weights is not the problem here).

Adding weights to the base RunningAverage library roughly doubles the RAM footprint, which is limited at the low end of the IOT spectrum. Therefor I have to be careful and prefer a separate derived class. Then users can select the class with or the class without weights. Only if a derived class is harder (whatever that means) than a new library the latter comes into sight.

Hope this helps to understand my thoughts around libraries in general and this issue specific.

**Comment by RobTillaart** [comment]
Spend a few hours trying to understand the definition of STDDEV and STDERR in context of a weighted running average.
no conclusion (code) yet

**Comment by heidnerd** [comment]
For testing -  a delay which might be something like    additional call to random number then -- delay (random(1,250);   OR simply use the value of the second call to the random number function  and then addValue (random(250) );

**Comment by RobTillaart** [comment]
So you only need the function **getSum()** ?

I was in the assumption you needed something far more different.
Still this investigation has learned me a few new things and even more new question ;)
So definitely worth the time spend.

**Comment by RobTillaart** [comment]
@heidnerd 
Redid the whole bunch ==> see develop branch + PR.

I have added a number of checks if the internal array was allocated for robustness.
This changed a number of return types, is backwards compatible.

Please verify if develop branch meet your needs.

**Comment by heidnerd** [comment]
Correct only getSum,  as simple as possible.   Yet that export makes it possible to create TWA by using two or more instances...

**Comment by RobTillaart** [comment]
> Correct only getSum, as simple as possible. Yet that export makes it possible to create TWA by using two or more instances...
> 
> I'll see about adding some links on how TWA is used with sensors to help estimate exposures and health risks.

Then I will merge the PR asap, there is an additional new function - see #31 - and some improved signatures.
Furthermore I will close this issue. Feel free to open a new issue if needed.

**Comment by heidnerd** [comment]
I saw #31 while I don't need it now, it will be useful.

Thanks,   I'll at some links and explanation.  I can also try doing a simple example sketch.

**Comment by RobTillaart** [comment]
**getSum()** is now in version 0.4.6, released a few minutes ago.

Again thanks for the issue, 
the "derived class weighted running average" is on my todo list and will appear sometime in the future.
